### ISSUE TITLE
RH network configuration missing ansible_managed

### ISSUE THREAD

**Issue by matsimon** [adfinis-sygroup/ansible-role-network#5]
I've successfully configure ethernet and bond interface on EL7 but discovered that unlike Debian it's currently missing a ansible_managed warning.

If @keachi doesn't come up with objections against, I'd make a pull request to include such a header
in [templates/etc/RedHat/header.j2](https://github.com/adfinis-sygroup/ansible-role-network/blob/master/templates/etc/RedHat/header.j2  )

**Comment by keachi** [comment]
Do it! There should be a header which says that.
